services:
  mongo:
    image: mongo:7
    container_name: vnmedid_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - vnmedid_network

  backend:
    build: ./backend
    container_name: vnmedid_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/vnmedid
      - JWT_SECRET=medical_blockchain_secret
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}
      - CONTRACT_USER=${CONTRACT_USER}
    depends_on:
      - mongo
    networks:
      - vnmedid_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vnmedid_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
    depends_on:
      - backend
    networks:
      - vnmedid_network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  vnmedid_network:
    driver: bridge